name: AndroidBuild

on:
  pull_request:
    branches:
      - main

jobs:
  connected-tests:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'
        
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          script: ./gradlew connectedCheck
