name: AndroidBuild

on:
  pull_request:
    branches:
      - main

jobs:
  connected-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          script: ./gradlew connectedCheck
